//
// AnnotationResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class AnnotationResponse: SaaSposeResponse {

    public var annotation: Annotation?


    

    // Encodable protocol methods

    public override func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(annotation, forKey: "Annotation")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        annotation = try container.decodeIfPresent(Annotation.self, forKey: "Annotation")
        try super.init(from: decoder)
    }
}

