//
// AnnotationsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class AnnotationsResponse: SaaSposeResponse {

    public var annotations: Annotations?


    

    // Encodable protocol methods

    public override func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(annotations, forKey: "Annotations")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        annotations = try container.decodeIfPresent(Annotations.self, forKey: "Annotations")
        try super.init(from: decoder)
    }
}

