//
// AntialiasingProcessingType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** This enum describes possible antialiasing measures during conversion */
public enum AntialiasingProcessingType: String, Codable {
    case noAdditionalProcessing = "NoAdditionalProcessing"
    case tryCorrectResultHtml = "TryCorrectResultHtml"

}
