//
// AppendDocument.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Class for appendDocument service request building. */

open class AppendDocument: Codable {

    /** Document to append (server path). */
    public var document: String?
    /** Appending start page. */
    public var startPage: Int
    /** Appending end page. */
    public var endPage: Int


    
    public init(document: String?, startPage: Int, endPage: Int) {
        self.document = document
        self.startPage = startPage
        self.endPage = endPage
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(document, forKey: "Document")
        try container.encode(startPage, forKey: "StartPage")
        try container.encode(endPage, forKey: "EndPage")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        document = try container.decodeIfPresent(String.self, forKey: "Document")
        startPage = try container.decode(Int.self, forKey: "StartPage")
        endPage = try container.decode(Int.self, forKey: "EndPage")
    }
}

