//
// AttachmentResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class AttachmentResponse: SaaSposeResponse {

    public var attachment: Attachment?


    

    // Encodable protocol methods

    public override func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(attachment, forKey: "Attachment")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        attachment = try container.decodeIfPresent(Attachment.self, forKey: "Attachment")
        try super.init(from: decoder)
    }
}

