//
// AttachmentsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class AttachmentsResponse: SaaSposeResponse {

    public var attachments: Attachments?


    

    // Encodable protocol methods

    public override func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(attachments, forKey: "Attachments")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        attachments = try container.decodeIfPresent(Attachments.self, forKey: "Attachments")
        try super.init(from: decoder)
    }
}

