//
// Color.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Represents color DTO. */

open class Color: Codable {

    public var A: Int
    public var R: Int
    public var G: Int
    public var B: Int


    
    public init(A: Int, R: Int, G: Int, B: Int) {
        self.A = A
        self.R = R
        self.G = G
        self.B = B
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(A, forKey: "A")
        try container.encode(R, forKey: "R")
        try container.encode(G, forKey: "G")
        try container.encode(B, forKey: "B")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        A = try container.decode(Int.self, forKey: "A")
        R = try container.decode(Int.self, forKey: "R")
        G = try container.decode(Int.self, forKey: "G")
        B = try container.decode(Int.self, forKey: "B")
    }
}

