//
// ColorDepth.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Used to specify the parameter value passed to a Tiff image device. */
public enum ColorDepth: String, Codable {
    case _default = "Default"
    case format8bpp = "Format8bpp"
    case format4bpp = "Format4bpp"
    case format1bpp = "Format1bpp"

}
