//
// CompressionType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Used to specify the parameter value passed to a Tiff image device. */
public enum CompressionType: String, Codable {
    case lzw = "LZW"
    case ccitt4 = "CCITT4"
    case ccitt3 = "CCITT3"
    case rle = "RLE"
    case _none = "None"

}
