//
// DocFormat.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Allows to specify .doc or .docx file format. */
public enum DocFormat: String, Codable {
    case doc = "Doc"
    case docX = "DocX"

}
