//
// DocRecognitionMode.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Allows to control how a PDF document is converted into a word processing document. */
public enum DocRecognitionMode: String, Codable {
    case textbox = "Textbox"
    case flow = "Flow"

}
