//
// DocumentResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class DocumentResponse: SaaSposeResponse {

    public var document: Document?
    public var messages: [String]?


    

    // Encodable protocol methods

    public override func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(document, forKey: "Document")
        try container.encodeIfPresent(messages, forKey: "Messages")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        document = try container.decodeIfPresent(Document.self, forKey: "Document")
        messages = try container.decodeIfPresent([String].self, forKey: "Messages")
        try super.init(from: decoder)
    }
}

