//
// DocumentProperty.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Pdf document property. */

open class DocumentProperty: LinkElement {

    public var name: String?
    public var value: String?
    public var builtIn: Bool?


    

    // Encodable protocol methods

    public override func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(name, forKey: "Name")
        try container.encodeIfPresent(value, forKey: "Value")
        try container.encodeIfPresent(builtIn, forKey: "BuiltIn")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        name = try container.decodeIfPresent(String.self, forKey: "Name")
        value = try container.decodeIfPresent(String.self, forKey: "Value")
        builtIn = try container.decodeIfPresent(Bool.self, forKey: "BuiltIn")
        try super.init(from: decoder)
    }
}

