//
// DocumentPagesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class DocumentPagesResponse: SaaSposeResponse {

    public var pages: Pages?


    

    // Encodable protocol methods

    public override func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(pages, forKey: "Pages")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        pages = try container.decodeIfPresent(Pages.self, forKey: "Pages")
        try super.init(from: decoder)
    }
}

