//
// EpubRecognitionMode.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** When PDF file (that usually has fixed layout) is being converted,             the conversion engine tries to perform grouping and multi-level analysis to restore             the original document author&#39;s intent and produce result in flow layout.  This property tunes that conversion for this or that             desirable method of recognition of content.              */
public enum EpubRecognitionMode: String, Codable {
    case flow = "Flow"
    case pdfFlow = "PdfFlow"
    case fixed = "Fixed"

}
