//
// Field.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Represents form field. */

open class Field: LinkElement {

    /** Field name. */
    public var name: String?
    /** Field type. */
    public var type: FieldType?
    /** Field values. */
    public var values: [String]?
    /** Selected items. */
    public var selectedItems: [Int]?
    /** Field rectangle. */
    public var rect: Rectangle?


    

    // Encodable protocol methods

    public override func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(name, forKey: "Name")
        try container.encodeIfPresent(type, forKey: "Type")
        try container.encodeIfPresent(values, forKey: "Values")
        try container.encodeIfPresent(selectedItems, forKey: "SelectedItems")
        try container.encodeIfPresent(rect, forKey: "Rect")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        name = try container.decodeIfPresent(String.self, forKey: "Name")
        type = try container.decodeIfPresent(FieldType.self, forKey: "Type")
        values = try container.decodeIfPresent([String].self, forKey: "Values")
        selectedItems = try container.decodeIfPresent([Int].self, forKey: "SelectedItems")
        rect = try container.decodeIfPresent(Rectangle.self, forKey: "Rect")
        try super.init(from: decoder)
    }
}

