//
// Fields.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** List of form fields. */

open class Fields: LinkElement {

    public var list: [Field]?


    

    // Encodable protocol methods

    public override func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(list, forKey: "List")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        list = try container.decodeIfPresent([Field].self, forKey: "List")
        try super.init(from: decoder)
    }
}

