//
// FieldType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Represents an enumeration of available field types. */
public enum FieldType: Int, Codable {
    case _0 = "0"
    case _1 = "1"
    case _2 = "2"
    case _3 = "3"

}
