//
// FieldResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class FieldResponse: SaaSposeResponse {

    public var field: Field?


    

    // Encodable protocol methods

    public override func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(field, forKey: "Field")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        field = try container.decodeIfPresent(Field.self, forKey: "Field")
        try super.init(from: decoder)
    }
}

