//
// FontStyles.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Specifies style information applied to text. */
public enum FontStyles: Int, Codable {
    case _0 = "0"
    case _1 = "1"
    case _2 = "2"

}
