//
// FontEncodingRules.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** This enumeration defines rules which tune encoding logic */
public enum FontEncodingRules: String, Codable {
    case _default = "Default"
    case decreaseToUnicodePriorityLevel = "DecreaseToUnicodePriorityLevel"

}
