//
// FontSavingModes.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Enumerates modes that can be used for saving of fonts referenced in saved PDF               */
public enum FontSavingModes: String, Codable {
    case alwaysSaveAsWOFF = "AlwaysSaveAsWOFF"
    case alwaysSaveAsTTF = "AlwaysSaveAsTTF"
    case alwaysSaveAsEOT = "AlwaysSaveAsEOT"
    case saveInAllFormats = "SaveInAllFormats"

}
