//
// HorizontalAlignment.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/**  */
public enum HorizontalAlignment: Int, Codable {
    case _0 = "0"
    case _1 = "1"
    case _2 = "2"
    case _3 = "3"

}
