//
// HtmlDocumentType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Represents enumeration of the Html document types. */
public enum HtmlDocumentType: String, Codable {
    case xhtml = "Xhtml"
    case html5 = "Html5"

}
