//
// HtmlMarkupGenerationModes.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Sometimes specific reqirments to created HTML are present. This enum defines HTML preparing modes that can be used during conversion of PDF to HTML to match such specific requirments.              */
public enum HtmlMarkupGenerationModes: String, Codable {
    case writeAllHtml = "WriteAllHtml"
    case writeOnlyBodyContent = "WriteOnlyBodyContent"

}
