//
// HttpStatusCode.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/**  */
public enum HttpStatusCode: Int, Codable {
    case _100 = "100"
    case _101 = "101"
    case _200 = "200"
    case _201 = "201"
    case _202 = "202"
    case _203 = "203"
    case _204 = "204"
    case _205 = "205"
    case _206 = "206"
    case _300 = "300"
    case _300 = "300"
    case _301 = "301"
    case _301 = "301"
    case _302 = "302"
    case _302 = "302"
    case _303 = "303"
    case _303 = "303"
    case _304 = "304"
    case _305 = "305"
    case _306 = "306"
    case _307 = "307"
    case _307 = "307"
    case _400 = "400"
    case _401 = "401"
    case _402 = "402"
    case _403 = "403"
    case _404 = "404"
    case _405 = "405"
    case _406 = "406"
    case _407 = "407"
    case _408 = "408"
    case _409 = "409"
    case _410 = "410"
    case _411 = "411"
    case _412 = "412"
    case _413 = "413"
    case _414 = "414"
    case _415 = "415"
    case _416 = "416"
    case _417 = "417"
    case _426 = "426"
    case _500 = "500"
    case _501 = "501"
    case _502 = "502"
    case _503 = "503"
    case _504 = "504"
    case _505 = "505"

}
