//
// Image.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Represents image DTO. */

open class Image: LinkElement {

    /** Gets width of the image. */
    public var width: Int?
    /** Gets height of the image. */
    public var height: Int?


    

    // Encodable protocol methods

    public override func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(width, forKey: "Width")
        try container.encodeIfPresent(height, forKey: "Height")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        width = try container.decodeIfPresent(Int.self, forKey: "Width")
        height = try container.decodeIfPresent(Int.self, forKey: "Height")
        try super.init(from: decoder)
    }
}

