//
// ImageResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class ImageResponse: SaaSposeResponse {

    public var image: Image?


    

    // Encodable protocol methods

    public override func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(image, forKey: "Image")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        image = try container.decodeIfPresent(Image.self, forKey: "Image")
        try super.init(from: decoder)
    }
}

