//
// ImagesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class ImagesResponse: SaaSposeResponse {

    public var images: Images?


    

    // Encodable protocol methods

    public override func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(images, forKey: "Images")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        images = try container.decodeIfPresent(Images.self, forKey: "Images")
        try super.init(from: decoder)
    }
}

