//
// LettersPositioningMethods.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** It enumerates possible modes of positioning of letters in words in result HTML              */
public enum LettersPositioningMethods: String, Codable {
    case useEmUnitsAndCompensationOfRoundingErrorsInCss = "UseEmUnitsAndCompensationOfRoundingErrorsInCss"
    case usePixelUnitsInCssLetterSpacingForIE = "UsePixelUnitsInCssLetterSpacingForIE"

}
