//
// LineSpacing.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/**  */
public enum LineSpacing: String, Codable {
    case fontSize = "FontSize"
    case fullSize = "FullSize"

}
