//
// LinkElement.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Represents base DTO object. */

open class LinkElement: Codable {

    /** Link to the document. */
    public var links: [Link]?


    
    public init(links: [Link]?) {
        self.links = links
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(links, forKey: "Links")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        links = try container.decodeIfPresent([Link].self, forKey: "Links")
    }
}

