//
// LinkAnnotationResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class LinkAnnotationResponse: SaaSposeResponse {

    public var link: LinkAnnotation?


    

    // Encodable protocol methods

    public override func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(link, forKey: "Link")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        link = try container.decodeIfPresent(LinkAnnotation.self, forKey: "Link")
        try super.init(from: decoder)
    }
}

