//
// LinkHighlightingMode.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Enumerates the annotation�s highlighting mode, the visual effect to be used when the mouse button is pressed or held down inside its active area. */
public enum LinkHighlightingMode: Int, Codable {
    case _0 = "0"
    case _1 = "1"
    case _2 = "2"
    case _3 = "3"
    case _4 = "4"

}
