//
// LinkAnnotationsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class LinkAnnotationsResponse: SaaSposeResponse {

    public var links: LinkAnnotations?


    

    // Encodable protocol methods

    public override func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(links, forKey: "Links")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        links = try container.decodeIfPresent(LinkAnnotations.self, forKey: "Links")
        try super.init(from: decoder)
    }
}

