//
// MergeDocuments.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Documents for merging. */

open class MergeDocuments: Codable {

    /** List of documents for merging. */
    public var list: [String]?


    
    public init(list: [String]?) {
        self.list = list
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(list, forKey: "List")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        list = try container.decodeIfPresent([String].self, forKey: "List")
    }
}

