//
// Page.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Provides link to page. */

open class Page: LinkElement {

    /** Page&#39;s id. */
    public var id: Int?
    public var images: Images?
    public var rectangle: Rectangle?


    

    // Encodable protocol methods

    public override func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(id, forKey: "Id")
        try container.encodeIfPresent(images, forKey: "Images")
        try container.encodeIfPresent(rectangle, forKey: "Rectangle")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        id = try container.decodeIfPresent(Int.self, forKey: "Id")
        images = try container.decodeIfPresent(Images.self, forKey: "Images")
        rectangle = try container.decodeIfPresent(Rectangle.self, forKey: "Rectangle")
        try super.init(from: decoder)
    }
}

