//
// PageTextReplaceResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class PageTextReplaceResponse: TextReplaceResponse {

    public var page: Page?


    

    // Encodable protocol methods

    public override func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(page, forKey: "Page")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        page = try container.decodeIfPresent(Page.self, forKey: "Page")
        try super.init(from: decoder)
    }
}

