//
// PartsEmbeddingModes.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** This enum enumerates possible modes of embedding of files referenced in HTML It allows to control whether referenced files (HTML, Fonts,Images, CSSes) will be embedded into main HTML file or will be generated as apart binary entities               */
public enum PartsEmbeddingModes: String, Codable {
    case embedAllIntoHtml = "EmbedAllIntoHtml"
    case embedCssOnly = "EmbedCssOnly"
    case noEmbedding = "NoEmbedding"

}
