//
// PdfAType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Allows to specify PdfA file format. */
public enum PdfAType: String, Codable {
    case pdfa1a = "PDFA1A"
    case pdfa1b = "PDFA1B"

}
