//
// RasterImagesSavingModes.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Converted PDF can contain raster images(.png, *.jpeg etc.) This enum defines methods of how raster images can be handled during conversion of PDF to HTML              */
public enum RasterImagesSavingModes: String, Codable {
    case asPngImagesEmbeddedIntoSvg = "AsPngImagesEmbeddedIntoSvg"
    case asExternalPngFilesReferencedViaSvg = "AsExternalPngFilesReferencedViaSvg"
    case asEmbeddedPartsOfPngPageBackground = "AsEmbeddedPartsOfPngPageBackground"

}
