//
// Rectangle.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Represents rectangle DTO. */

open class Rectangle: Codable {

    public var X: Int
    public var Y: Int
    public var width: Int
    public var height: Int


    
    public init(X: Int, Y: Int, width: Int, height: Int) {
        self.X = X
        self.Y = Y
        self.width = width
        self.height = height
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(X, forKey: "X")
        try container.encode(Y, forKey: "Y")
        try container.encode(width, forKey: "Width")
        try container.encode(height, forKey: "Height")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        X = try container.decode(Int.self, forKey: "X")
        Y = try container.decode(Int.self, forKey: "Y")
        width = try container.decode(Int.self, forKey: "Width")
        height = try container.decode(Int.self, forKey: "Height")
    }
}

