//
// Rotation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Enumeration of possible rotation values. */
public enum Rotation: Int, Codable {
    case _0 = "0"
    case _1 = "1"
    case _2 = "2"
    case _3 = "3"

}
