//
// Segment.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class Segment: Codable {

    public var value: String?
    public var textState: TextState?


    
    public init(value: String?, textState: TextState?) {
        self.value = value
        self.textState = textState
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(value, forKey: "Value")
        try container.encodeIfPresent(textState, forKey: "TextState")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        value = try container.decodeIfPresent(String.self, forKey: "Value")
        textState = try container.decodeIfPresent(TextState.self, forKey: "TextState")
    }
}

