//
// ShapeType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** This enum represents shape type for the extracted images. */
public enum ShapeType: String, Codable {
    case _none = "None"
    case landscape = "Landscape"
    case portrait = "Portrait"

}
