//
// SignatureVerifyResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Returns also a message. */

open class SignatureVerifyResponse: SaaSposeResponse {

    /** Valid sign. */
    public var valid: Bool?


    

    // Encodable protocol methods

    public override func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(valid, forKey: "Valid")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        valid = try container.decodeIfPresent(Bool.self, forKey: "Valid")
        try super.init(from: decoder)
    }
}

