//
// SplitResultResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Represents split result object. */

open class SplitResultResponse: SaaSposeResponse {

    /** Gets or sets the splitting result. */
    public var result: SplitResult?


    

    // Encodable protocol methods

    public override func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(result, forKey: "Result")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        result = try container.decodeIfPresent(SplitResult.self, forKey: "Result")
        try super.init(from: decoder)
    }
}

