//
// SplitResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Represents split result object. */

open class SplitResult: Codable {

    /** Gets or sets the list of documents. */
    public var documents: [SplitResultDocument]?


    
    public init(documents: [SplitResultDocument]?) {
        self.documents = documents
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(documents, forKey: "Documents")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        documents = try container.decodeIfPresent([SplitResultDocument].self, forKey: "Documents")
    }
}

