//
// TextFormat.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Represents text format DTO. */

open class TextFormat: LinkElement {

    public var color: Color?
    public var fontSize: Double?
    public var fontName: String?


    

    // Encodable protocol methods

    public override func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(color, forKey: "Color")
        try container.encodeIfPresent(fontSize, forKey: "FontSize")
        try container.encodeIfPresent(fontName, forKey: "FontName")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        color = try container.decodeIfPresent(Color.self, forKey: "Color")
        fontSize = try container.decodeIfPresent(Double.self, forKey: "FontSize")
        fontName = try container.decodeIfPresent(String.self, forKey: "FontName")
        try super.init(from: decoder)
    }
}

