//
// TextHorizontalAlignment.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/**  */
public enum TextHorizontalAlignment: String, Codable {
    case _left = "Left"
    case _right = "Right"
    case center = "Center"
    case justify = "Justify"
    case fullJustify = "FullJustify"
    case _none = "None"

}
