//
// TextRect.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Represents text DTO. */

open class TextRect: Codable {

    public var text: String?
    public var page: Int
    public var rect: Rectangle?


    
    public init(text: String?, page: Int, rect: Rectangle?) {
        self.text = text
        self.page = page
        self.rect = rect
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(text, forKey: "Text")
        try container.encode(page, forKey: "Page")
        try container.encodeIfPresent(rect, forKey: "Rect")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        text = try container.decodeIfPresent(String.self, forKey: "Text")
        page = try container.decode(Int.self, forKey: "Page")
        rect = try container.decodeIfPresent(Rectangle.self, forKey: "Rect")
    }
}

