//
// TextReplaceListRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Multiple text replacements request. */

open class TextReplaceListRequest: Codable {

    /** A list of text replacement settings. */
    public var textReplaces: [TextReplace]
    public var defaultFont: String?
    public var startIndex: Int?
    public var countReplace: Int?


    
    public init(textReplaces: [TextReplace], defaultFont: String?, startIndex: Int?, countReplace: Int?) {
        self.textReplaces = textReplaces
        self.defaultFont = defaultFont
        self.startIndex = startIndex
        self.countReplace = countReplace
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(textReplaces, forKey: "TextReplaces")
        try container.encodeIfPresent(defaultFont, forKey: "DefaultFont")
        try container.encodeIfPresent(startIndex, forKey: "StartIndex")
        try container.encodeIfPresent(countReplace, forKey: "CountReplace")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        textReplaces = try container.decode([TextReplace].self, forKey: "TextReplaces")
        defaultFont = try container.decodeIfPresent(String.self, forKey: "DefaultFont")
        startIndex = try container.decodeIfPresent(Int.self, forKey: "StartIndex")
        countReplace = try container.decodeIfPresent(Int.self, forKey: "CountReplace")
    }
}

