//
// TextLine.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A line of text to be inserted into . */

open class TextLine: Codable {

    /** Line&#39;s horizontal alignment */
    public var horizontalAlignment: TextHorizontalAlignment?
    /** Segments that form the line. Every segment has its own formatting. */
    public var segments: [Segment]?


    
    public init(horizontalAlignment: TextHorizontalAlignment?, segments: [Segment]?) {
        self.horizontalAlignment = horizontalAlignment
        self.segments = segments
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(horizontalAlignment, forKey: "HorizontalAlignment")
        try container.encodeIfPresent(segments, forKey: "Segments")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        horizontalAlignment = try container.decodeIfPresent(TextHorizontalAlignment.self, forKey: "HorizontalAlignment")
        segments = try container.decodeIfPresent([Segment].self, forKey: "Segments")
    }
}

