//
// TextItemResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class TextItemResponse: SaaSposeResponse {

    public var textItem: TextItem?


    

    // Encodable protocol methods

    public override func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(textItem, forKey: "TextItem")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        textItem = try container.decodeIfPresent(TextItem.self, forKey: "TextItem")
        try super.init(from: decoder)
    }
}

