//
// TextItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Represents text DTO. */

open class TextItem: LinkElement {

    public var text: String?
    public var format: TextFormat?


    

    // Encodable protocol methods

    public override func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(text, forKey: "Text")
        try container.encodeIfPresent(format, forKey: "Format")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        text = try container.decodeIfPresent(String.self, forKey: "Text")
        format = try container.decodeIfPresent(TextFormat.self, forKey: "Format")
        try super.init(from: decoder)
    }
}

