//
// TextReplaceResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class TextReplaceResponse: SaaSposeResponse {

    public var matches: Int?


    

    // Encodable protocol methods

    public override func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(matches, forKey: "Matches")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        matches = try container.decodeIfPresent(Int.self, forKey: "Matches")
        try super.init(from: decoder)
    }
}

