//
// TextRects.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Represents text items DTO. */

open class TextRects: Codable {

    public var list: [TextRect]?


    
    public init(list: [TextRect]?) {
        self.list = list
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(list, forKey: "List")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        list = try container.decodeIfPresent([TextRect].self, forKey: "List")
    }
}

