//
// TextRectsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class TextRectsResponse: SaaSposeResponse {

    public var textOccurences: TextRects?


    

    // Encodable protocol methods

    public override func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(textOccurences, forKey: "TextOccurences")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        textOccurences = try container.decodeIfPresent(TextRects.self, forKey: "TextOccurences")
        try super.init(from: decoder)
    }
}

