//
// TextFormatResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class TextFormatResponse: SaaSposeResponse {

    public var textFormat: TextFormat?


    

    // Encodable protocol methods

    public override func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(textFormat, forKey: "TextFormat")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        textFormat = try container.decodeIfPresent(TextFormat.self, forKey: "TextFormat")
        try super.init(from: decoder)
    }
}

