//
// VerticalAlignment.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Enumeration of possible vertical alignment values. */
public enum VerticalAlignment: String, Codable {
    case _none = "None"
    case top = "Top"
    case center = "Center"
    case bottom = "Bottom"

}
