//
// WordCountResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Number of words per document pages. */

open class WordCountResponse: SaaSposeResponse {

    /** with words per page info.             */
    public var wordsPerPage: WordCount?


    

    // Encodable protocol methods

    public override func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(wordsPerPage, forKey: "WordsPerPage")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        wordsPerPage = try container.decodeIfPresent(WordCount.self, forKey: "WordsPerPage")
        try super.init(from: decoder)
    }
}

