//
// WrapMode.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/**  */
public enum WrapMode: String, Codable {
    case noWrap = "NoWrap"
    case byWords = "ByWords"
    case discretionaryHyphenation = "DiscretionaryHyphenation"

}
